let words = [
{ inputs: 6, catagory: "fruit", word: "orange", hint: "A citrus fruit with a bright orange color" },
{ inputs: 6, catagory: "vegetable", word: "carrot", hint: "A root vegetable that is often orange in color" },
{ inputs: 3, catagory: "animal", word: "dog", hint: "A domesticated mammal that is often kept as a pet" },
{ inputs: 4, catagory: "color", word: "blue", hint: "The color of the sky on a clear day" },
{ inputs: 3, catagory: "body part", word: "ear", hint: "The organ responsible for hearing and maintaining balance" },
{ inputs: 4, catagory: "vehicle", word: "bike", hint: "A two-wheeled vehicle that is often powered by a motor" },
{ inputs: 7, catagory: "city", word: "chicago", hint: "A city in the state of Illinois, known for its architecture and deep-dish pizza" },
{ inputs: 4, catagory: "plant", word: "rose", hint: "A woody perennial flowering plant that comes in many different colors" },
{ inputs: 7, catagory: "bird", word: "sparrow", hint: "A small, brown songbird that is common in many parts of the world" },
{ inputs: 6, catagory: "drink", word: "coffee", hint: "A popular hot beverage made from the roasted seeds of the Coffea plant" },
{ inputs: 9, catagory: "insect", word: "butterfly", hint: "A flying insect with brightly colored wings, known for its beauty and grace" },
{ inputs: 7, catagory: "ocean", word: "pacific", hint: "The largest ocean in the world, stretching from the Arctic to the Antarctic" },
{ inputs: 6, catagory: "tool", word: "hammer", hint: "A hand tool with a heavy head and a handle, used for driving nails or breaking objects" },
{ inputs: 3, catagory: "tree", word: "oak", hint: "A tree that is known for its strength and durability, and is commonly used in furniture and construction" },
{ inputs: 4, catagory: "river", word: "nile", hint: "The longest river in the world, flowing through northeastern Africa and emptying into the Mediterranean Sea" },
{ inputs: 7, catagory: "mountain", word: "everest", hint: "The highest mountain in the world, located in the Himalayas on the border between Nepal and China" },
{ inputs: 5, catagory: "flower", word: "daisy", hint: "A common flower with a white petals and a yellow center, often associated with innocence and purity" },
{ inputs: 5, catagory: "furniture", word: "chair", hint: "A piece of furniture with a seat, back, and arms, used for sitting" },
{ inputs: 6, catagory: "country", word: "canada", hint: "A country in North America, known for its natural beauty, diversity, and friendly people" },
{ inputs: 4, catagory: "planet", word: "mars", hint: "The fourth planet from the sun, known as the Red Planet due to its reddish appearance" },
{ inputs: 3, catagory: "animal", word: "cat", hint: "A small, carnivorous mammal that is often kept as a pet" },
{ inputs: 5, catagory: "color", word: "green", hint: "The color of grass and trees, associated with nature and growth" },
{ inputs: 3, catagory: "body part", word: "eye", hint: "The organ responsible for vision and one of the most important sensory organs in the human body" },
{ inputs: 3, catagory: "vehicle", word: "car", hint: "A four-wheeled vehicle that is powered by an engine and used for transportation" },
{ inputs: 5, catagory: "city", word: "paris", hint: "The capital city of France, known for its art, fashion, and cuisine" },
{ inputs: 9, catagory: "plant", word: "sunflower", hint: "A tall, yellow flower that follows the sun and is often associated with happiness and positivity" },
{ inputs: 5, catagory: "fruit", word: "apple", hint: "A sweet fruit that comes in many varieties and is often eaten raw or used in pies" },
{ inputs: 8, catagory: "animal", word: "elephant", hint: "A large mammal with a long trunk and tusks, native to Africa and parts of Asia" },
{ inputs: 3, catagory: "color", word: "red", hint: "The color of blood, fire, and roses, associated with passion and love" },
{ inputs: 4, catagory: "body part", word: "nose", hint: "The organ responsible for smelling and a prominent feature of the human face" },
{ inputs: 5, catagory: "vehicle", word: "train", hint: "A long vehicle that runs on tracks and is used for transportation, especially of passengers or goods" },
{ inputs: 5, catagory: "city", word: "tokyo", hint: "The capital city of Japan, known for its modernity, technology, and pop culture" },
{ inputs: 5, catagory: "plant", word: "tulip", hint: "A perennial flowering plant that is native to Asia and Europe and is often associated with the Netherlands" },
]
