let words = [
{ inputs: 6, catagory: "fruit", word: "orange", hint: "A citrus fruit with a bright orange color" },
{ inputs: 6, catagory: "vegetable", word: "carrot", hint: "A root vegetable that is often orange in color" },
{ inputs: 3, catagory: "animal", word: "dog", hint: "A domesticated mammal that is often kept as a pet" },
{ inputs: 4, catagory: "color", word: "blue", hint: "The color of the sky on a clear day" },
{ inputs: 3, catagory: "body part", word: "ear", hint: "The organ responsible for hearing and maintaining balance" },
{ inputs: 4, catagory: "vehicle", word: "bike", hint: "A two-wheeled vehicle that is often powered by a motor" },
{ inputs: 7, catagory: "city", word: "chicago", hint: "A city in the state of Illinois, known for its architecture and deep-dish pizza" },
{ inputs: 4, catagory: "plant", word: "rose", hint: "A woody perennial flowering plant that comes in many different colors" },
{ inputs: 7, catagory: "bird", word: "sparrow", hint: "A small, brown songbird that is common in many parts of the world" },
{ inputs: 6, catagory: "drink", word: "coffee", hint: "A popular hot beverage made from the roasted seeds of the Coffea plant" },
{ inputs: 9, catagory: "insect", word: "butterfly", hint: "A flying insect with brightly colored wings, known for its beauty and grace" },
{ inputs: 7, catagory: "ocean", word: "pacific", hint: "The largest ocean in the world, stretching from the Arctic to the Antarctic" },
{ inputs: 6, catagory: "tool", word: "hammer", hint: "A hand tool with a heavy head and a handle, used for driving nails or breaking objects" },
{ inputs: 3, catagory: "tree", word: "oak", hint: "A tree that is known for its strength and durability, and is commonly used in furniture and construction" },
{ inputs: 4, catagory: "river", word: "nile", hint: "The longest river in the world, flowing through northeastern Africa and emptying into the Mediterranean Sea" },
{ inputs: 7, catagory: "mountain", word: "everest", hint: "The highest mountain in the world, located in the Himalayas on the border between Nepal and China" },
{ inputs: 5, catagory: "flower", word: "daisy", hint: "A common flower with a white petals and a yellow center, often associated with innocence and purity" },
{ inputs: 5, catagory: "furniture", word: "chair", hint: "A piece of furniture with a seat, back, and arms, used for sitting" },
{ inputs: 6, catagory: "country", word: "canada", hint: "A country in North America, known for its natural beauty, diversity, and friendly people" },
{ inputs: 4, catagory: "planet", word: "mars", hint: "The fourth planet from the sun, known as the Red Planet due to its reddish appearance" },
{ inputs: 3, catagory: "animal", word: "cat", hint: "A small, carnivorous mammal that is often kept as a pet" },
{ inputs: 5, catagory: "color", word: "green", hint: "The color of grass and trees, associated with nature and growth" },
{ inputs: 3, catagory: "body part", word: "eye", hint: "The organ responsible for vision and one of the most important sensory organs in the human body" },
{ inputs: 3, catagory: "vehicle", word: "car", hint: "A four-wheeled vehicle that is powered by an engine and used for transportation" },
{ inputs: 5, catagory: "city", word: "paris", hint: "The capital city of France, known for its art, fashion, and cuisine" },
{ inputs: 9, catagory: "plant", word: "sunflower", hint: "A tall, yellow flower that follows the sun and is often associated with happiness and positivity" },
{ inputs: 5, catagory: "fruit", word: "apple", hint: "A sweet fruit that comes in many varieties and is often eaten raw or used in pies" },
{ inputs: 8, catagory: "animal", word: "elephant", hint: "A large mammal with a long trunk and tusks, native to Africa and parts of Asia" },
{ inputs: 3, catagory: "color", word: "red", hint: "The color of blood, fire, and roses, associated with passion and love" },
{ inputs: 4, catagory: "body part", word: "nose", hint: "The organ responsible for smelling and a prominent feature of the human face" },
{ inputs: 5, catagory: "vehicle", word: "train", hint: "A long vehicle that runs on tracks and is used for transportation, especially of passengers or goods" },
{ inputs: 5, catagory: "city", word: "tokyo", hint: "The capital city of Japan, known for its modernity, technology, and pop culture" },
{ inputs: 5, catagory: "plant", word: "tulip", hint: "A perennial flowering plant that is native to Asia and Europe and is often associated with the Netherlands" },
{ inputs: 6, catagory:a"sport", word: "soccer", hint: "A popular game played with a round ball and feet" },
{ inputs: 7, catagory: "movie", word: "avatar", hint: "A science fiction film directed by James Cameron" },
{ inputs: 9, catagory: "technology", word: "smartphone", hint: "A mobile device that can make calls, send messages, and run apps" },
{ inputs: 7, catagory: "music", word: "guitar", hint: "A stringed instrument often used in rock and folk music" },
{ inputs: 8, catagory: "food", word: "pasta", hint: "A dish made from unleavened dough, typically with sauce" },
{ inputs: 7, catagory: "book", word: "harrypotter", hint: "A series of fantasy novels written by J.K. Rowling" },
{ inputs: 6, catagory: "vehicle", word: "bicycle", hint: "A two-wheeled vehicle propelled by pedaling" },
{ inputs: 8, catagory: "holiday", word: "halloween", hint: "A festive holiday celebrated on October 31st with costumes and candy" },
{ inputs: 10, catagory: "animal", word: "butterfly", hint: "An insect with colorful wings that flutters gracefully" },
{ inputs: 5, catagory: "animal", word: "tiger", hint: "A large striped cat known for its strength and agility" },
{ inputs: 6, catagory: "country", word: "brazil", hint: "A South American country famous for its Amazon rainforest" },
{ inputs: 8, catagory: "historical", word: "pyramids", hint: "Ancient structures found in Egypt, often associated with pharaohs" },
{ inputs: 7, catagory: "color", word: "maroon", hint: "A dark red color, often associated with wine" },
{ inputs: 9, catagory: "profession", word: "firefighter", hint: "Someone who extinguishes fires and rescues people" },
{ inputs: 10, catagory: "fictional", word: "dragonscale", hint: "A mythical material often associated with dragons" },
{ inputs: 9, catagory: "fictional", word: "superhero", hint: "A character with extraordinary abilities, often fighting crime" },
{ inputs: 8, catagory: "science", word: "chemistry", hint: "The study of matter, its properties, and interactions" },
{ inputs: 7, catagory: "music", word: "pianist", hint: "Someone who plays the piano professionally" },
{ inputs: 7, catagory: "country", word: "germany", hint: "A European country known for beer, sausages, and Oktoberfest" },
{ inputs: 8, catagory: "movie", word: "inception", hint: "A mind-bending film directed by Christopher Nolan" },
{ inputs: 10, catagory: "technology", word: "augmented", hint: "Enhancing or supplementing reality using computer-generated information" },
{ inputs: 8, catagory: "fictional", word: "vampire", hint: "A mythical creature that feeds on blood" },
{ inputs: 6, catagory: "sport", word: "tennis", hint: "A racket sport played on a court divided by a net" },
{ inputs: 7, catagory: "food", word: "chocolate", hint: "A sweet treat made from cocoa beans" },
{ inputs: 11, catagory: "literature", word: "adventurous", hint: "Full of excitement, exploration, and risk-taking" },
{ inputs: 8, catagory: "animal", word: "elephant", hint: "A large mammal with a trunk and tusks" },
{ inputs: 9, catagory: "country", word: "australia", hint: "A country known for its kangaroos, koalas, and Outback" },
{ inputs: 6, catagory: "color", word: "yellow", hint: "A bright color often associated with sunshine" },
{ inputs: 9, catagory: "science", word: "astronomy", hint: "The study of celestial objects and phenomena" },
{ inputs: 7, catagory: "music", word: "symphony", hint: "A long musical composition typically divided into multiple movements" },
{ inputs: 8, catagory: "food", word: "sandwich", hint: "A meal consisting of ingredients between two slices of bread" },
{ inputs: 7, catagory: "vehicle", word: "airplane", hint: "A powered flying vehicle used for transportation" },
{ inputs: 7, catagory: "fictional", word: "unicorn", hint: "A mythical horse-like creature with a single horn" },
{ inputs: 6, catagory: "sport", word: "cricket", hint: "A bat-and-ball game played between two teams" },
{ inputs: 9, catagory: "literature", word: "adventure", hint: "An exciting or daring experience or activity" },
{ inputs: 10, catagory: "technology", word: "programming", hint: "The process of writing code for computer software" },
{ inputs: 7, catagory: "movie", word: "titanic", hint: "A film based on the sinking of the RMS Titanic" },
{ inputs: 8, catagory: "animal", word: "cheetah", hint: "A large, fast-running feline known for its spotted coat" },
{ inputs: 9, catagory: "country", word: "argentina", hint: "A South American country known for tango and steak" },
{ inputs: 8, catagory: "color", word: "turquoise", hint: "A blue-green mineral often used in jewelry" },
{ inputs: 10, catagory: "science", word: "technology", hint: "The application of scientific knowledge for practical purposes" },
{ inputs: 6, catagory: "music", word: "violin", hint: "A stringed instrument played with a bow" },
{ inputs: 8, catagory: "food", word: "hamburger", hint: "A sandwich consisting of a cooked patty of ground meat" },
{ inputs: 8, catagory: "vehicle", word: "motorbike", hint: "A two-wheeled vehicle powered by a motor" },
{ inputs: 10, catagory: "fictional", word: "mermaidtail", hint: "The lower part of a mythical creature with the body of a fish and the upper body of a human" },
]
